/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Aluno;
import model.Curso;

/**
 *
 * @author joaov
 */
public class MatriculaCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form MatriculaCurso
     */
    public MatriculaCurso() {
        initComponents();
        Cadastro cad = new Cadastro();
        for(Curso c : cad.cursos){
            jComboCurso.addItem(c.getTitulo());
        }
        for(Aluno a : cad.alunos){
           jComboAluno.addItem(a.getNome());
        }
        jComboCurso.setSelectedIndex(-1);
        jComboAluno.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jComboCurso = new javax.swing.JComboBox<>();
        jComboAluno = new javax.swing.JComboBox<>();
        txtMes = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        Curso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        labelValor = new javax.swing.JLabel();
        labelProfessor = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        jLabel6.setText("jLabel6");

        jButton4.setText("jButton4");

        setTitle("Inscrição Curso");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil_go.png"))); // NOI18N

        jComboCurso.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboCursoMouseMoved(evt);
            }
        });

        txtMatricula.setToolTipText("");

        Curso.setText("Curso");

        jLabel2.setText("Aluno");

        jLabel3.setText("Matrícula");

        jLabel4.setText("Mês");

        jLabel5.setText("Ano");

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMatricula)
                        .addComponent(jComboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btCancelar)))))
                    .addComponent(Curso)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btCadastrar))
                    .addComponent(jComboAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Curso)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar)
                    .addComponent(btLimpar)
                    .addComponent(btCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtAno.setText("");
        txtMatricula.setText("");
        txtMes.setText("");
        jComboAluno.setSelectedIndex(-1);
        jComboCurso.setSelectedIndex(-1);
        labelProfessor.setText("");
        labelValor.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Cadastro cad = new Cadastro();
        String nomecurso = jComboCurso.getSelectedItem().toString();
        for(Curso c : cad.cursos) {
            if(c.getVagas() > 0) {
                if(nomecurso.equals(c.getTitulo())) {
                    int numvagas = c.getVagas();
                    c.setVagas(numvagas-1);
                    JOptionPane.showMessageDialog(null, "O aluno " + jComboAluno.getSelectedItem().toString() + " foi matriculado no curso " + nomecurso + " com sucesso!");
                    txtAno.setText("");
                    txtMatricula.setText("");
                    txtMes.setText("");
                    jComboAluno.setSelectedIndex(-1);
                    jComboCurso.setSelectedIndex(-1);
                    labelProfessor.setText("");
                    labelValor.setText("");
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Não há mais vagas no curso!");
            }
        }
        
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void jComboCursoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboCursoMouseMoved
        if(jComboCurso.getSelectedIndex() != -1) {
            Cadastro cad = new Cadastro();
            String nomecurso = jComboCurso.getSelectedItem().toString();
            for(Curso c : cad.cursos) {
                if(nomecurso.equals(c.getTitulo())) {
                    String nomeprofessor = c.getProfessor();
                    Double valor = c.getValor();
                    labelProfessor.setText("Professor: " + nomeprofessor);
                    labelValor.setText("Valor: R$ " + valor.toString());
                }
            }
        }
    }//GEN-LAST:event_jComboCursoMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Curso;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboAluno;
    private javax.swing.JComboBox<String> jComboCurso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelProfessor;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMes;
    // End of variables declaration//GEN-END:variables
}
